### ISSUE TITLE
关于数据

### ISSUE THREAD

**Issue by szxSpark** [Nrgeup/chinese_semantic_role_labeling#2]
请问data文件夹下的cpbtrain.txt, cpbdev.txt, cpbtest.txt 是你对cpb原始文件预处理后生成的文件吗。如果是的话，请问你的cpb原始文件是cpb1.0、cpb2.0、cpb3.0中哪个版本呀

**Comment by Nrgeup** [comment]
不知道，这是一个课程作业，数据集老师由提供的，应该只是某个cpb的一小部分，全部的是收费的。
